version: "3.9"

services:

  database:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=avista
      - POSTGRES_PASSWORD=avistapw
      - POSTGRES_DB=avista_db
    restart: always

  backend:
    build: ./server
    command: gunicorn --bind 0.0.0.0:5000 --workers=4 app:app
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: always

  frontend:
    build: ./client
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
