version: "3.9"

services:

  backend:
    build: ./server
    command: gunicorn3 --bind 0.0.0.0:5000 --workers=4 app:app
    ports:
      - "5000:5000"
    privileged: True

  frontend:
    build: ./client
    ports:
      - "8080:8080"