version: "3.9"

services:

  backend:
    build: ./server
    command: gunicorn3 --bind 0.0.0.0:5000 --workers=4 app:app
    privileged: True
    network_mode: host

  frontend:
    build: ./client
    ports:
      - "8080:8080"