version: "3.9"

services:

  backend:
    image: isuese/avista-iot-server:latest
    command: /usr/bin/python3 app.py
    network_mode: host
    privileged: True
    restart: always

  frontend:
    image: isuese/avista-iot-client:latest
    network_mode: host
    
  data:
    image: isuese/avista-iot-data:latest
    command: /usr/bin/python3 app.py
    network_mode: host
    privileged: True
