#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

cd server
docker buildx build \
       --platform linux/arm/v7 \
       --build-arg dbtype=postgres \
       --build-arg dbname=avistadb \
       --build-arg dbuser=avista \
       --build-arg dbpass=avistapw \
       --build-arg dbip=localhost \
       --build-arg dbport=5432 \
       --build-arg hostname=0.0.0.0 \
       --build-arg hostport=5000 \
       -t isuese/avista-iot-server:latest \
       .
docker push isuese/avista-iot-server:latest

cd ../client
docker buildx build --platform linux/arm/v7 -t isuese/avista-iot-client:latest .
docker push isuese/avista-iot-client:latest
