dbdata:
  - item: DBMS Type
    type: text
    value: sqlite
  - item: DBMS DB Name
    type: text
    value: test.db
  - item: DBMS IP Address
    type: text
    value: /./test-data
  - item: DBMS Port
    type: text
    value: ''
service:
  host: localhost
  port: '5000'
sysdata:
  - item: System Identifier
    type: text
    value: 1542138f6a794288844e92f027fa0b31
  - item: Equipment Monitored
    type: text
    value: ''
  - item: Location
    type: text
    value: ''
  - item: Data Collection Periodicity (ms)
    type: number
    value: 5000
  - item: Server Port
    type: number
    value: 5000